FROM maven:3.3-jdk-8
MAINTAINER Martin Peters

WORKDIR /root
VOLUME /root/.m2/repository

# directory containing all the source code folders
ENV SRC_DIR "/root/src"

ADD scripts/build_masymos.sh /root/build_masymos.sh

CMD "/root/build_masymos.sh"
